### ISSUE TITLE
GEtting Fatal Error

### ISSUE THREAD

**Issue by tapashi** [dequelabs/grunt-axe-webdriver#24]
I have installed grunt-axe-webdriver.
But when I am trying to run "grunt" I am getting following error.

> Running "axe-webdriver:chrome" (axe-webdriver) task
> Fatal error: Timed out waiting for the WebDriver server at http://127.0.0.1:5959
> 5/hub

Can Anyone help me , how to fix that issue.
Please note: I am not an expert in development

**Comment by WilcoFiers** [comment]
@tapashi There is quite a number of things that could go wrong that causes a timeout. Do you have the latest version of the Chrome webdriver installed?

**Comment by tapashi** [comment]
Yes I have tried that also. May be I have done it wrong . can you please suggest the steps so that I can check it again

**Comment by WilcoFiers** [comment]
Have a look here: https://sites.google.com/a/chromium.org/chromedriver/getting-started Google does an excellent job of documenting this proces. Also make sure that the server is running. If you swap your URL for something on the web (`http://deque.com` for example), and that works, the problem is probably with the server.

**Comment by marcysutton** [comment]
I'm going to close this issue for inactivity, please reopen if it persists.

**Comment by dmorgenstern-init** [comment]
I have a similar issue. See #35.
